// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a text template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------


namespace Nine.Graphics.Views
{
    /// <summary>
    /// Content reader for <c>DirectionalLightView</c>.
    /// <summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Reader.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    class DirectionalLightViewReader : Microsoft.Xna.Framework.Content.ContentTypeReader<Nine.Graphics.Views.DirectionalLightView>
    {
        protected override Nine.Graphics.Views.DirectionalLightView Read(Microsoft.Xna.Framework.Content.ContentReader input, Nine.Graphics.Views.DirectionalLightView existingInstance)
        {
            if (existingInstance == null)
            {
                var graphicsDeviceService = (Microsoft.Xna.Framework.Graphics.IGraphicsDeviceService)input.ContentManager.ServiceProvider.GetService(
                                      typeof(Microsoft.Xna.Framework.Graphics.IGraphicsDeviceService));
                existingInstance = new DirectionalLightView(graphicsDeviceService.GraphicsDevice);
            }
            existingInstance.CastShadow = input.ReadObject<System.Boolean>();
            existingInstance.DiffuseColor = input.ReadObject<Microsoft.Xna.Framework.Vector3>();
            existingInstance.Direction = input.ReadObject<Microsoft.Xna.Framework.Vector3>();
            existingInstance.Enabled = input.ReadObject<System.Boolean>();
            existingInstance.Order = input.ReadObject<System.Single>();
            existingInstance.SpecularColor = input.ReadObject<Microsoft.Xna.Framework.Vector3>();

            return existingInstance;
        }
    }
    /// <summary>
    /// Content reader for <c>ModelView</c>.
    /// <summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Reader.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    class ModelViewReader : Microsoft.Xna.Framework.Content.ContentTypeReader<Nine.Graphics.Views.ModelView>
    {
        protected override Nine.Graphics.Views.ModelView Read(Microsoft.Xna.Framework.Content.ContentReader input, Nine.Graphics.Views.ModelView existingInstance)
        {
            if (existingInstance == null)
            {
                existingInstance = new ModelView();
            }
            existingInstance.Effect = input.ReadObject<Microsoft.Xna.Framework.Graphics.Effect>();
            existingInstance.Model = input.ReadObject<Microsoft.Xna.Framework.Graphics.Model>();
            existingInstance.Transform = input.ReadObject<Microsoft.Xna.Framework.Matrix>();
            existingInstance.Visible = input.ReadObject<System.Boolean>();

            return existingInstance;
        }
    }
    /// <summary>
    /// Content reader for <c>ParticleEffectView</c>.
    /// <summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Reader.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    class ParticleEffectViewReader : Microsoft.Xna.Framework.Content.ContentTypeReader<Nine.Graphics.Views.ParticleEffectView>
    {
        protected override Nine.Graphics.Views.ParticleEffectView Read(Microsoft.Xna.Framework.Content.ContentReader input, Nine.Graphics.Views.ParticleEffectView existingInstance)
        {
            if (existingInstance == null)
            {
                existingInstance = new ParticleEffectView();
            }
            existingInstance.ParticleEffect = input.ReadObject<Nine.Graphics.ParticleEffects.ParticleEffect>();
            existingInstance.Position = input.ReadObject<Microsoft.Xna.Framework.Vector3>();
            existingInstance.Visible = input.ReadObject<System.Boolean>();

            return existingInstance;
        }
    }
    /// <summary>
    /// Content reader for <c>ViewTemplate</c>.
    /// <summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Reader.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    class ViewTemplateReader : Microsoft.Xna.Framework.Content.ContentTypeReader<Nine.Graphics.Views.ViewTemplate>
    {
        protected override Nine.Graphics.Views.ViewTemplate Read(Microsoft.Xna.Framework.Content.ContentReader input, Nine.Graphics.Views.ViewTemplate existingInstance)
        {
            if (existingInstance == null)
            {
                existingInstance = new ViewTemplate();
            }
            existingInstance.Views = input.ReadObject<System.Collections.Generic.List<Nine.Graphics.IDrawableView>>();
            existingInstance.Visible = input.ReadObject<System.Boolean>();

            return existingInstance;
        }
    }
}
