// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a text template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------


namespace Nine.Graphics
{
    /// <summary>
    /// Content reader for <c>DirectionalLight</c>.
    /// <summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Reader.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    class DirectionalLightReader : Microsoft.Xna.Framework.Content.ContentTypeReader<Nine.Graphics.DirectionalLight>
    {
        protected override Nine.Graphics.DirectionalLight Read(Microsoft.Xna.Framework.Content.ContentReader input, Nine.Graphics.DirectionalLight existingInstance)
        {
            if (existingInstance == null)
            {
                var graphicsDeviceService = (Microsoft.Xna.Framework.Graphics.IGraphicsDeviceService)input.ContentManager.ServiceProvider.GetService(
                                      typeof(Microsoft.Xna.Framework.Graphics.IGraphicsDeviceService));
                existingInstance = new DirectionalLight(graphicsDeviceService.GraphicsDevice);
            }
            existingInstance.CastShadow = input.ReadObject<System.Boolean>();
            existingInstance.DiffuseColor = input.ReadObject<Microsoft.Xna.Framework.Vector3>();
            existingInstance.Direction = input.ReadObject<Microsoft.Xna.Framework.Vector3>();
            existingInstance.Enabled = input.ReadObject<System.Boolean>();
            existingInstance.Order = input.ReadObject<System.Single>();
            existingInstance.SpecularColor = input.ReadObject<Microsoft.Xna.Framework.Vector3>();

            return existingInstance;
        }
    }
    /// <summary>
    /// Content reader for <c>ModelInstance</c>.
    /// <summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Reader.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    class ModelInstanceReader : Microsoft.Xna.Framework.Content.ContentTypeReader<Nine.Graphics.ModelInstance>
    {
        protected override Nine.Graphics.ModelInstance Read(Microsoft.Xna.Framework.Content.ContentReader input, Nine.Graphics.ModelInstance existingInstance)
        {
            if (existingInstance == null)
            {
                existingInstance = new ModelInstance();
            }
            existingInstance.Effect = input.ReadObject<Microsoft.Xna.Framework.Graphics.Effect>();
            existingInstance.Model = input.ReadObject<Microsoft.Xna.Framework.Graphics.Model>();
            existingInstance.Transform = input.ReadObject<Microsoft.Xna.Framework.Matrix>();
            existingInstance.Visible = input.ReadObject<System.Boolean>();

            return existingInstance;
        }
    }
    /// <summary>
    /// Content reader for <c>ParticleEffectInstance</c>.
    /// <summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Reader.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    class ParticleEffectInstanceReader : Microsoft.Xna.Framework.Content.ContentTypeReader<Nine.Graphics.ParticleEffectInstance>
    {
        protected override Nine.Graphics.ParticleEffectInstance Read(Microsoft.Xna.Framework.Content.ContentReader input, Nine.Graphics.ParticleEffectInstance existingInstance)
        {
            if (existingInstance == null)
            {
                existingInstance = new ParticleEffectInstance();
            }
            existingInstance.ParticleEffect = input.ReadObject<Nine.Graphics.ParticleEffects.ParticleEffect>();
            existingInstance.Position = input.ReadObject<Microsoft.Xna.Framework.Vector3>();
            existingInstance.Visible = input.ReadObject<System.Boolean>();

            return existingInstance;
        }
    }
    /// <summary>
    /// Content reader for <c>ViewTemplate</c>.
    /// <summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Reader.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    class ViewTemplateReader : Microsoft.Xna.Framework.Content.ContentTypeReader<Nine.Graphics.ViewTemplate>
    {
        protected override Nine.Graphics.ViewTemplate Read(Microsoft.Xna.Framework.Content.ContentReader input, Nine.Graphics.ViewTemplate existingInstance)
        {
            if (existingInstance == null)
            {
                existingInstance = new ViewTemplate();
            }
            existingInstance.Views = input.ReadObject<System.Collections.Generic.List<System.Object>>();
            existingInstance.Visible = input.ReadObject<System.Boolean>();

            return existingInstance;
        }
    }
}
