// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a text template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------

#if !TEXT_TEMPLATE
namespace Nine.Content.Pipeline
{
    /// <summary>
    /// Content writer for <c>BounceCurve</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class BounceCurveContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<BounceCurveContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, BounceCurveContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, BounceCurveContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, BounceCurveContent value)
        {
            BeginWrite(output, value);
            output.Write(value.Strength);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.BounceCurveReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.BounceCurve, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>CustomCurve</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class CustomCurveContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<CustomCurveContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, CustomCurveContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, CustomCurveContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, CustomCurveContent value)
        {
            BeginWrite(output, value);
            output.WriteObject(value.Curve);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.CustomCurveReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.CustomCurve, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>ElasticCurve</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class ElasticCurveContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<ElasticCurveContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, ElasticCurveContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, ElasticCurveContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, ElasticCurveContent value)
        {
            BeginWrite(output, value);
            output.Write(value.Strength);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.ElasticCurveReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.ElasticCurve, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>ExponentialCurve</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class ExponentialCurveContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<ExponentialCurveContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, ExponentialCurveContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, ExponentialCurveContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, ExponentialCurveContent value)
        {
            BeginWrite(output, value);
            output.Write(value.Power);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.ExponentialCurveReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.ExponentialCurve, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>LinearCurve</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class LinearCurveContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<LinearCurveContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, LinearCurveContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, LinearCurveContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, LinearCurveContent value)
        {
            BeginWrite(output, value);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.LinearCurveReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.LinearCurve, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>SinCurve</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class SinCurveContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<SinCurveContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, SinCurveContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, SinCurveContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, SinCurveContent value)
        {
            BeginWrite(output, value);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.SinCurveReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.SinCurve, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>SmoothCurve</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class SmoothCurveContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<SmoothCurveContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, SmoothCurveContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, SmoothCurveContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, SmoothCurveContent value)
        {
            BeginWrite(output, value);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.SmoothCurveReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.SmoothCurve, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
}
namespace Nine.Content.Pipeline.Animations
{
    /// <summary>
    /// Content writer for <c>AnimationPlayer</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class AnimationPlayerContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<AnimationPlayerContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, AnimationPlayerContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, AnimationPlayerContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, AnimationPlayerContent value)
        {
            BeginWrite(output, value);
            output.WriteObject(value.Animations);
            output.WriteObject(value.Tag);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.AnimationPlayerReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.AnimationPlayer, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>DelayAnimation</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class DelayAnimationContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<DelayAnimationContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, DelayAnimationContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, DelayAnimationContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, DelayAnimationContent value)
        {
            BeginWrite(output, value);
            output.WriteObject(value.Duration);
            output.Write(value.Speed);
            output.Write(value.AutoReverse);
            output.WriteObject(value.StartupDirection);
            output.WriteObject(value.Direction);
            output.Write(value.Repeat);
            output.WriteObject(value.Position);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.DelayAnimationReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.DelayAnimation, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>LayeredAnimation</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class LayeredAnimationContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<LayeredAnimationContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, LayeredAnimationContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, LayeredAnimationContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, LayeredAnimationContent value)
        {
            BeginWrite(output, value);
            output.WriteObject(value.Animations);
            output.Write(value.Repeat);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.LayeredAnimationReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.LayeredAnimation, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>SequentialAnimation</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class SequentialAnimationContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<SequentialAnimationContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, SequentialAnimationContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, SequentialAnimationContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, SequentialAnimationContent value)
        {
            BeginWrite(output, value);
            output.WriteObject(value.Animations);
            output.Write(value.Repeat);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.SequentialAnimationReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.SequentialAnimation, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>TransformAnimation</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class TransformAnimationContentWriter : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<TransformAnimationContent>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, TransformAnimationContent value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, TransformAnimationContent value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, TransformAnimationContent value)
        {
            BeginWrite(output, value);
            output.WriteObject(value.TargetProperty);
            output.WriteObject(value.ScaleX);
            output.WriteObject(value.ScaleY);
            output.WriteObject(value.ScaleZ);
            output.WriteObject(value.RotationOrder);
            output.WriteObject(value.RotationX);
            output.WriteObject(value.RotationY);
            output.WriteObject(value.RotationZ);
            output.WriteObject(value.X);
            output.WriteObject(value.Y);
            output.WriteObject(value.Z);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.TransformAnimationReader, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.TransformAnimation, Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
    /// <summary>
    /// Content writer for <c>TweenAnimation`1</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Writer.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter]
    partial class TweenAnimationContentWriter<T> : Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentTypeWriter<TweenAnimationContent<T>>
    {
        partial void BeginWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, TweenAnimationContent<T> value);
        partial void EndWrite(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, TweenAnimationContent<T> value);        
        
        protected override void Write(Microsoft.Xna.Framework.Content.Pipeline.Serialization.Compiler.ContentWriter output, TweenAnimationContent<T> value)
        {
            BeginWrite(output, value);
            output.WriteObject(value.From);
            output.WriteObject(value.To);
            output.WriteObject(value.By);
            output.WriteObject(value.Easing);
            output.WriteObject(value.Curve);
            output.WriteObject(value.Duration);
            output.WriteObject(value.TargetProperty);
            output.Write(value.Speed);
            output.Write(value.AutoReverse);
            output.WriteObject(value.StartupDirection);
            output.WriteObject(value.Direction);
            output.Write(value.Repeat);
            output.WriteObject(value.Position);
            EndWrite(output, value);
        }

        public override string GetRuntimeReader(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.TweenAnimationReader`1[" + string.Format("[{0}]", typeof(T).AssemblyQualifiedName) + "], Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }

        public override string GetRuntimeType(Microsoft.Xna.Framework.Content.Pipeline.TargetPlatform targetPlatform)
        {
            return "Nine.Animations.TweenAnimation`1[" + string.Format("[{0}]", typeof(T).AssemblyQualifiedName) + "], Nine, Version=1.2.0.0, Culture=neutral, PublicKeyToken=ed8336b5652212a9";
        }
    }
}
#endif