// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a text template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// -----------------------------------------------------------------------------


#if !TEXT_TEMPLATE
namespace Nine.Content.Pipeline
{
    /// <summary>
    /// Content model for <c>BounceCurve</c>.
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.BounceCurve, Nine")]
    public partial class BounceCurveContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("0.2")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Single Strength { get; set; }

        /// <summary>
        /// Initializes a new instance of <c>BounceCurveContent</c>.
        /// </summary>
        public BounceCurveContent()
        {
            Strength = (System.Single)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Single)).ConvertFromInvariantString("0.2");
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>CustomCurve</c>.
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.CustomCurve, Nine")]
    public partial class CustomCurveContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual Nine.Content.Pipeline.ContentReference<Microsoft.Xna.Framework.Curve> Curve { get; set; }

        /// <summary>
        /// Initializes a new instance of <c>CustomCurveContent</c>.
        /// </summary>
        public CustomCurveContent()
        {
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>ElasticCurve</c>.
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.ElasticCurve, Nine")]
    public partial class ElasticCurveContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("0.2")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Single Strength { get; set; }

        /// <summary>
        /// Initializes a new instance of <c>ElasticCurveContent</c>.
        /// </summary>
        public ElasticCurveContent()
        {
            Strength = (System.Single)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Single)).ConvertFromInvariantString("0.2");
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>ExponentialCurve</c>.
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.ExponentialCurve, Nine")]
    public partial class ExponentialCurveContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("0.03125")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Single Power { get; set; }

        /// <summary>
        /// Initializes a new instance of <c>ExponentialCurveContent</c>.
        /// </summary>
        public ExponentialCurveContent()
        {
            Power = (System.Single)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Single)).ConvertFromInvariantString("0.03125");
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>LinearCurve</c>.
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.LinearCurve, Nine")]
    public partial class LinearCurveContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// Initializes a new instance of <c>LinearCurveContent</c>.
        /// </summary>
        public LinearCurveContent()
        {
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>SinCurve</c>.
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.SinCurve, Nine")]
    public partial class SinCurveContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// Initializes a new instance of <c>SinCurveContent</c>.
        /// </summary>
        public SinCurveContent()
        {
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>SmoothCurve</c>.
    /// 
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.SmoothCurve, Nine")]
    public partial class SmoothCurveContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// Initializes a new instance of <c>SmoothCurveContent</c>.
        /// </summary>
        public SmoothCurveContent()
        {
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
}
namespace Nine.Content.Pipeline.Animations
{
    /// <summary>
    /// Content model for <c>AnimationPlayer</c>.
    /// Represents a basic animation player that can play multiple animation sequences using different channels.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.Animations.AnimationPlayer, Nine")]
    public partial class AnimationPlayerContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Collections.Generic.Dictionary<System.String, System.Object> Animations { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Object Tag { get; set; }

        /// <summary>
        /// Initializes a new instance of <c>AnimationPlayerContent</c>.
        /// </summary>
        public AnimationPlayerContent()
        {
            Animations = new System.Collections.Generic.Dictionary<System.String, System.Object>();
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>DelayAnimation</c>.
    /// An dummy animation that completes after the specified duration. This is usually used with SequentialAnimation to delay the playing of subsequent animations.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.Animations.DelayAnimation, Nine")]
    public partial class DelayAnimationContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("00:00:00")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.TimeSpan Duration { get; set; }

        /// <summary>
        /// Initializes a new instance of <c>DelayAnimationContent</c>.
        /// </summary>
        public DelayAnimationContent()
        {
            Duration = (System.TimeSpan)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.TimeSpan)).ConvertFromInvariantString("00:00:00");
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>LayeredAnimation</c>.
    /// Contains several animation clips that are played concurrently. The animation completes when all of its containing animations had finished playing.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.Animations.LayeredAnimation, Nine")]
    public partial class LayeredAnimationContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Collections.Generic.List<System.Object> Animations { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("1")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Int32 Repeat { get; set; }

        /// <summary>
        /// Initializes a new instance of <c>LayeredAnimationContent</c>.
        /// </summary>
        public LayeredAnimationContent()
        {
            Animations = new System.Collections.Generic.List<System.Object>();
            Repeat = (System.Int32)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Int32)).ConvertFromInvariantString("1");
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>SequentialAnimation</c>.
    /// Contains several animation clips that are played one after another. The animation completes when the last animation has finished playing.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.Animations.SequentialAnimation, Nine")]
    public partial class SequentialAnimationContent : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Collections.Generic.List<System.Object> Animations { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("1")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Int32 Repeat { get; set; }

        /// <summary>
        /// Initializes a new instance of <c>SequentialAnimationContent</c>.
        /// </summary>
        public SequentialAnimationContent()
        {
            Animations = new System.Collections.Generic.List<System.Object>();
            Repeat = (System.Int32)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Int32)).ConvertFromInvariantString("1");
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
    /// <summary>
    /// Content model for <c>TweenAnimation`1</c>.
    /// Implements a basic primitive animation that changes its value over time. Can also update the value of a named target property on an target object.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Content.Model.tt", "1.1.0.0")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [Microsoft.Xna.Framework.Content.ContentSerializerRuntimeType("Nine.Animations.TweenAnimation`1, Nine")]
    public partial class TweenAnimationContent<T> : System.Xaml.IAttachedPropertyStore
    {
        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("False")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Boolean AutoReverse { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Nullable<System.TimeSpan> BeginTime { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Nullable<T> By { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.TypeConverter(typeof(Nine.Content.Pipeline.Design.CurveConverter))]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Object Curve { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("Forward")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual Nine.Animations.AnimationDirection Direction { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("00:00:01")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.TimeSpan Duration { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("In")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual Nine.Animations.Easing Easing { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Nullable<System.TimeSpan> EndTime { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Nullable<T> From { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("00:00:00")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.TimeSpan Position { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("1")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Single Repeat { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("1")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Single Speed { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [System.ComponentModel.DefaultValue("Forward")]
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual Nine.Animations.AnimationDirection StartupDirection { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.String TargetProperty { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [Microsoft.Xna.Framework.Content.ContentSerializer(Optional = true)]
        public virtual System.Nullable<T> To { get; set; }

        /// <summary>
        /// Initializes a new instance of <c>TweenAnimationContent</c>.
        /// </summary>
        public TweenAnimationContent()
        {
            AutoReverse = (System.Boolean)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Boolean)).ConvertFromInvariantString("False");
            Direction = (Nine.Animations.AnimationDirection)System.ComponentModel.TypeDescriptor.GetConverter(typeof(Nine.Animations.AnimationDirection)).ConvertFromInvariantString("Forward");
            Duration = (System.TimeSpan)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.TimeSpan)).ConvertFromInvariantString("00:00:01");
            Easing = (Nine.Animations.Easing)System.ComponentModel.TypeDescriptor.GetConverter(typeof(Nine.Animations.Easing)).ConvertFromInvariantString("In");
            Position = (System.TimeSpan)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.TimeSpan)).ConvertFromInvariantString("00:00:00");
            Repeat = (System.Single)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Single)).ConvertFromInvariantString("1");
            Speed = (System.Single)System.ComponentModel.TypeDescriptor.GetConverter(typeof(System.Single)).ConvertFromInvariantString("1");
            StartupDirection = (Nine.Animations.AnimationDirection)System.ComponentModel.TypeDescriptor.GetConverter(typeof(Nine.Animations.AnimationDirection)).ConvertFromInvariantString("Forward");
            OnCreate();
        }

        partial void OnCreate();

        #region IAttachedPropertyStore
        System.Collections.Generic.IDictionary<System.Xaml.AttachableMemberIdentifier, object> attachedProperties = new System.Collections.Generic.Dictionary<System.Xaml.AttachableMemberIdentifier, object>();

        void System.Xaml.IAttachedPropertyStore.CopyPropertiesTo(System.Collections.Generic.KeyValuePair<System.Xaml.AttachableMemberIdentifier, object>[] array, int index)
        {
            attachedProperties.CopyTo(array, index);
        }

        int System.Xaml.IAttachedPropertyStore.PropertyCount
        {
            get { return attachedProperties.Count; }
        }

        bool System.Xaml.IAttachedPropertyStore.RemoveProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier)
        {
            return attachedProperties.Remove(attachableMemberIdentifier);
        }

        void System.Xaml.IAttachedPropertyStore.SetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, object value)
        {
            attachedProperties[attachableMemberIdentifier] = value;
        }

        bool System.Xaml.IAttachedPropertyStore.TryGetProperty(System.Xaml.AttachableMemberIdentifier attachableMemberIdentifier, out object value)
        {
            return attachedProperties.TryGetValue(attachableMemberIdentifier, out value);
        }
        #endregion
    }
}
#endif